version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.41
    ports:
      - "16686:16686"    # Jaeger UI
      - "14268:14268"    # Jaeger collector

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"

  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: