spring.datasource.url=jdbc:postgresql://localhost:5433/user
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis config if needed
spring.redis.host=localhost
spring.redis.port=6379